-- AG Analytics: initial database schema
-- Run with: wrangler d1 execute ag_analytics_db --remote --file=./migrations/0001_init.sql

-- Dashboard administrators (people who log in to view stats)
CREATE TABLE IF NOT EXISTS admins (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  login TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  email TEXT,
  created_at INTEGER NOT NULL
);

-- Every tracked website ("site") lives here
CREATE TABLE IF NOT EXISTS sites (
  id TEXT PRIMARY KEY,              -- short public id, used in tracker.js as data-site
  name TEXT NOT NULL,
  domain TEXT NOT NULL,
  description TEXT,
  api_key TEXT NOT NULL UNIQUE,     -- secret key, never exposed to the browser
  status TEXT NOT NULL DEFAULT 'active', -- active | disabled
  created_at INTEGER NOT NULL
);

-- One row per page view / hit collected by tracker.js
CREATE TABLE IF NOT EXISTS visits (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  site_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  visitor_hash TEXT NOT NULL,       -- daily-rotating anonymous hash, never a cookie or IP
  url TEXT NOT NULL,
  page_title TEXT,
  referrer TEXT,
  referrer_domain TEXT,
  search_engine TEXT,
  search_query TEXT,
  utm_source TEXT,
  utm_medium TEXT,
  utm_campaign TEXT,
  utm_term TEXT,
  utm_content TEXT,
  browser TEXT,
  os TEXT,
  device_type TEXT,
  screen_resolution TEXT,
  language TEXT,
  timezone TEXT,
  country TEXT,
  duration_seconds INTEGER DEFAULT 0,
  created_at INTEGER NOT NULL,
  FOREIGN KEY (site_id) REFERENCES sites (id)
);

-- Lightweight session table, used for bounce rate and average time on site
CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,              -- session_id, generated by tracker.js and kept in memory only
  site_id TEXT NOT NULL,
  visitor_hash TEXT NOT NULL,
  page_count INTEGER NOT NULL DEFAULT 1,
  first_seen INTEGER NOT NULL,
  last_seen INTEGER NOT NULL,
  FOREIGN KEY (site_id) REFERENCES sites (id)
);

-- Custom events / goals (e.g. "signup", "purchase"), reported manually by the
-- site owner via window.agEvent(name, props) — see public/tracker.js.
-- Separate from `visits` on purpose: not every page load is an event, and not
-- every event happens on a page load.
CREATE TABLE IF NOT EXISTS events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  site_id TEXT NOT NULL,
  session_id TEXT,
  visitor_hash TEXT NOT NULL,
  name TEXT NOT NULL,
  url TEXT,
  props TEXT,                       -- optional JSON-encoded key/value metadata
  created_at INTEGER NOT NULL,
  FOREIGN KEY (site_id) REFERENCES sites (id)
);

CREATE INDEX IF NOT EXISTS idx_visits_site_created ON visits (site_id, created_at);
CREATE INDEX IF NOT EXISTS idx_visits_site_url ON visits (site_id, url);
CREATE INDEX IF NOT EXISTS idx_visits_site_country ON visits (site_id, country);
CREATE INDEX IF NOT EXISTS idx_visits_site_referrer ON visits (site_id, referrer_domain);
CREATE INDEX IF NOT EXISTS idx_visits_site_browser ON visits (site_id, browser);
CREATE INDEX IF NOT EXISTS idx_visits_site_os ON visits (site_id, os);
CREATE INDEX IF NOT EXISTS idx_visits_site_device ON visits (site_id, device_type);
CREATE INDEX IF NOT EXISTS idx_sessions_site ON sessions (site_id, last_seen);
CREATE INDEX IF NOT EXISTS idx_events_site_created ON events (site_id, created_at);
CREATE INDEX IF NOT EXISTS idx_events_site_name ON events (site_id, name);
